[elastic]
host = "http://es.example.com:9200"
username = "es_user"
password = "securepass123"
timeout_secs = 180
connect_timeout_secs = 60

[backup]
backup_dir = "./backups"
scroll_size = 10000
scroll_time = "10m"
max_parallel_indices = 4
skip_indices = []

[restore]
bulk_batch_size = 5000
